# Generated by Django 5.0.6 on 2024-05-31 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=63)),
                ('date_registration', models.DateField(auto_now_add=True)),
                ('subscription_end_date', models.DateField(default=datetime.date(2024, 5, 31))),
            ],
        ),
    ]
