# Generated by Django 5.0.6 on 2024-05-31 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableReaderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 31, 11, 2, 28, 599753, tzinfo=datetime.timezone.utc)),
        ),
    ]
