# Generated by Django 5.0.6 on 2024-06-30 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableReaderApp', '0002_alter_user_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 10, 36, 17, 70478, tzinfo=datetime.timezone.utc)),
        ),
    ]
