# Generated by Django 5.0.6 on 2024-07-01 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableReaderApp', '0003_alter_user_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 1, 17, 23, 31, 813733, tzinfo=datetime.timezone.utc)),
        ),
    ]
